description = "Update each repo’s plugin in the right markdown section, then create REASON.md summarizing why each category was chosen."

prompt = """
## Workflow

1. Read the category index in @.claude/SECTION.md and memorize each referenced file and the sections it contains.
2. Read **one line** from the following list of repositories.
3. Visit the corresponding repository on **GitHub**.
4. Skip further processing if any of these conditions apply:
   4.1. The plugin is a fork of another repository.
   4.2. It is a new colorscheme plugin.
   4.3. The plugin is non‑functional or unfinished.
   4.4. The repository has no README.
   4.5. The README is written in a language other than English.
   4.6. The repository is a Neovim configuration rather than a plugin.
   4.7. The repository is a sample plugin created solely for learning purposes.
5. From the README or other files, **infer which Neovim‑plugin category** the repository belongs to.
6. In `@.claude/SECTION.md`, consult the table of contents and locate the markdown file that contains that category.
7. Open that markdown file and insert the new plugin at the appropriate position.  
   7.1. If no suitable section exists, create one first and then add the plugin.  
   7.2. If there are subsections, review them and add the plugin to the **most appropriate subsection** whenever possible.
   7.3. Add new plugins at the bottom of the section.
   7.4. If there are related plugins, list them below the relevant plugin.
8. Because the work must be done within **Gemini’s free quota**, **wait one minute** after finishing each repository.
9. After all repositories have been processed, list the evidence for each plugin’s categorization in a markdown table (`|URL|Category|Reason|`) and save it as **`REASON.md`**.

{{args}}
"""
