name: Count by account

on:
  push:
    branches:
      - main

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: >
          grep '](https://github.com' [a-z]*.md | sed -re 's/^.*\]\(https:\/\/github.com\/([^\)]*).*/\1/' | xargs -I {} dirname {} | sort | uniq -c | sort -n -r
