name: Trigger new rss

on:
  push:
    branches:
      - main

jobs:
  github:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - run: |
          apt update
          apt-get install -y git curl
      - run: git clone ${{ github.server_url }}/${{ github.repository }}
      - name: latest commit message
        run: |
          echo LATEST_MESSAGE=$(git log --no-merges -n 1 --pretty=%s) >> $GITHUB_ENV
        working-directory: ${{ github.event.repository.name }}
      - name: check commit message
        run: echo $LATEST_MESSAGE
      - run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/yutkat/new-neovim-plugin-with-category-rss/dispatches -d '{"event_type":"trigger-new-repo"}'
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        if: startsWith(env.LATEST_MESSAGE,'Add')
        working-directory: ${{ github.event.repository.name }}
